DROP TABLE IF EXISTS `persons`;
CREATE TABLE `persons` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `firstname` varchar(255) NOT NULL,
  PRIMARY KEY  (`id`),
) DEFAULT CHARSET=utf8;

INSERT INTO `persons` VALUES INSERT INTO `persons` VALUES (1,'Mr','Dubois','Gabriel'),
(2,'Mr','Martinez','Raphael'),
(3,'Mr','Leroy','Lucas'),
(4,'Mr','Perrin','Tom'),
(5,'Mme','Fournier','Chloe'),
(6,'Mme','Durand','Ines'),
(7,'Mr','Guerin','Maxime'),
(8,'Mme','Garcia','Jade'),
(9,'Mme','Faure','Eva'),
(10,'Mr','Lefebvre','Jules'),
(11,'Mme','Dubois','Lea'),
(12,'Mr','Perrin','Lucas'),
(13,'Mme','Fournier','Clara'),
(14,'Mme','Moreau','Camille'),
(15,'Mr','Durand','Lucas'),
(16,'Mme','Morel','Camille'),
(17,'Mr','Bonnet','Maxime'),
(18,'Mme','Perrin','Manon'),
(19,'Mr','Morel','Lucas'),
(20,'Mr','Martinez','Nathan'),
(21,'Mr','Lambert','Thomas'),
(22,'Mr','Girard','Matheo'),
(23,'Mme','Dumont','Lola'),
(24,'Mme','Morin','Chloe'),
(25,'Mr','Mercier','Raphael'),
(26,'Mr','Martinez','Mathis'),
(27,'Mr','Garcia','Theo'),
(28,'Mr','Girard','Nathan'),
(29,'Mr','Henry','Thomas'),
(30,'Mr','Mercier','Mathis'),
(31,'Mme','Leroy','Clara'),
(32,'Mme','Dupont','Zoe'),
(33,'Mr','Dupont','Mathis'),
(34,'Mr','Blanc','Raphael'),
(35,'Mr','Dupont','Maxime'),
(36,'Mr','Garnier','Nathan'),
(37,'Mme','Petit','Clara'),
(38,'Mme','Garnier','Lea'),
(39,'Mr','Mercier','Louis'),
(40,'Mme','Dubois','Zoe'),
(41,'Mme','Durand','Sarah'),
(42,'Mme','Muller','Eva'),
(43,'Mr','Fournier','Hugo'),
(44,'Mr','Garnier','Tom'),
(45,'Mr','Garcia','Theo'),
(46,'Mr','Fournier','Gabriel'),
(47,'Mr','Garnier','Theo'),
(48,'Mme','Garnier','Lea'),
(49,'Mr','Blanc','Maxime'),
(50,'Mr','Lefebvre','Mathis');


